cnages in workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,14 +38,14 @@ jobs:
               run: |
                   ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << EOF
                   if [ ! -d "pipeline" ]; then
-                  git clone ${{github.event.repository.clone_url}}
-                  cd pipeline
+                      git clone ${{github.event.repository.clone_url}}
+                      cd pipeline
                   else
-                  cd pipeline
-                  git pull origin main
+                      cd pipeline
+                      git pull origin main
                   fi
-                  npm run manage_node
-                  npm run manage_pm2
+                  npm run manage_node || echo "Failed to run manage_node"
+                  npm run manage_pm2 || echo "Failed to run manage_pm2"
                   EOF
               env:
                   EC2_HOST: ${{secrets.EC2_HOST}}
